spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: 9xiErz03ZCb3E24LWKCRdMzMXWaJLXoJ
            client-secret: HUVFJGo6ob9Kwe-36iCUIxZnwSs3_Cc1NBH1Pl8GjdFVxMg2vucvTg2yXy-tdZaW
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            issuer-uri: https://dev-iqwsuwq0hjdquab4.us.auth0.com/
